### ISSUE TITLE
[iw3] *.flv conversion fails silently

### ISSUE THREAD

**Issue by lilacs2039** [nagadomi/nunif#116]
Thank you for this wonderful app!

mp4 videos worked fine.
But when I ran the flv video it silently failed(simply shows 完了), so I wondered what was going on. (Finally, I realized that the video file format was probably not supported.)

Therefore, it will be easier to use if you do one of the following:
- If the file format is not supported, the cause of the error will be displayed in the status bar.
- Display execution log in separate tab
- Appropriately set the extension filter on the file selection screen (disable flv selection)
- Compatible with multiple file formats

**Comment by nagadomi** [comment]
This problem seems to happen only on Windows.
On my Linux env, iw3 can process flv normally.
However, I confirmed that on Windows it shows "完了" without doing anything.

Maybe pyav(ffmpeg binding) for windows is not built to support flv. I'll look it up.

**Comment by nagadomi** [comment]
Fixed https://github.com/nagadomi/nunif/commit/657e81cd4283803013e0eeb3876f5361a36f117d. flv video file is now supported on Windows.

The cause of the problem was that the mimetype for .flv is not defined on Windows, so .flv file was not processed as a video file.
Also, if the file type is not recognized, error is shown. https://github.com/nagadomi/nunif/commit/5c3c5e4b4e35830189c6ae032a3e6bc1c0937c20
