### ISSUE TITLE
Why doesn't waifu reduce the noise for this type of image?

### ISSUE THREAD

**Issue by shuttittuppitt** [nagadomi/nunif#165]
I have several images that have a specific type of noise in them, & since waifu has a noise reducing function, I tried using waifu to reduce the noise of one of the images. (I only tried noise reduction on it, not size increasing.) The problem is that even waifu's maximum noise reduction level doesn't seem to reduce the noise at all. I'm including the image that I tested it with as an attachment. Does waifu not consider the type of noise that this kind of image has to meet it's definition of noise?

![b-04](https://github.com/nagadomi/nunif/assets/56204774/230b1d1c-a096-4ba5-8c8c-c4cc040dabf6)

**Comment by nagadomi** [comment]
Yes, it is not noise. It's paper or cloth texture.
`Art` model reduces JPEG noise only.
`Art/Scan` model support paper texture removal. But it does not expect watercolor like input.

**Comment by shuttittuppitt** [comment]
Yeah, the images that I have (that have that type of texture) are scans of _physical_ book pages that I scanned in order to make _digital_ copies of them. (Oddly, the structure of the (physical) textures is tight enough that I didn't notice that they were using a "printed dithering texture" (although I should've expected that) until I scanned them & then saw the texturing in the digital scans. I then checked the physical pages with a magnifying app, & confirmed that they _do_ use "printed dithering textures", so it's not caused by the scanner.)

Anyway, waifu's art/scan mode _does_ do what I was trying to do, so thanks for bringing that mode to my attention. (I always use "swin_unet/photo" with denoise set to "low").

**Comment by nagadomi** [comment]
These days, 2D artists sometimes intentionally use perlin noise, for example. I do not want to remove textures, gradients, blurs, etc. that the artist intended. So, in `Art` model for digital illustrations, I basically consider JPEG compression noise is the only noise that should be removed.
However, printed art and further scanning of it can produce various noises due to various factors such as paper, scanner, and camera. `Art/Scan` model aims to target such input.
