### ISSUE TITLE
Export Disparity generates and saves the second copy

### ISSUE THREAD

**Issue by romanr** [nagadomi/nunif#176]
1. I ran Export Disparity, video stored on a SMB network drive. Noticed that it's doing a lot of i/o comparing to regular 3D SBS generation. 
2. Stopped and set Output to local Disk C
3. Started (Resume enabled). it went way faster.
4. Once it reached the end it started doing another run but this time saving on network drive next to the original Video

**Comment by nagadomi** [comment]
As for resume, if you change the output drive/directory, you must move the original output directory yourself.
Otherwise, it will run from the beginning and the original output directory will still have the previous output.
As for the progress bar, the first shows the progress of the audio export, the second shows the progress of the frame and depth exports.
I guess there is some confusion due to this behavior.

As for I/O, it can be parallelized by increasing `Worker Threads` setting, but I am sure that network drive is slow.
