### ISSUE TITLE
Package not downloading

### ISSUE THREAD

**Issue by Cobalixe** [nagadomi/nunif#215]
It gets stuck when downloading the models for iw3

**Comment by nagadomi** [comment]
Is it a problem while running `instat.bat` in `nunif-windows-package`? Or another OS or command?
Is it stuck with no error message?

The model used by iw3 is more than 1 GB, so if the network is slow, it may take longer.
If you get SSL related error for huggingface, it may be caused by VPN.

See also https://github.com/nagadomi/nunif/issues/122 How to download models manually

**Comment by Cobalixe** [comment]
> Is it a problem while running `instat.bat` in `nunif-windows-package`? Or another OS or command? Is it stuck with no error message?
> 
> The model used by iw3 is more than 1 GB, so if the network is slow, it may take longer. If you get SSL related error for huggingface, it may be caused by VPN.
> 
> See also #122 How to download models manually

I run the install.bat and all goes fine until it gets to the iw3 models, it gets stuck while downloading one of the repositories, "zipball" I think it's called.

Will try to download manually and run it again to see if it skips that part.

**Comment by nagadomi** [comment]
Perhaps it's just slow download speed.
I don't know how long it was stuck, but the comment in #122 says it can take 10-20 minutes.

**Comment by Cobalixe** [comment]
seems to be that, I sweared I waited more time last time and didn't downlaod.
