### ISSUE TITLE
Cannot get local network working

### ISSUE THREAD

**Issue by matthewn4444** [nagadomi/nunif#220]
Hello, I was able to setup and install web on my local computer and can run it from the browser, however I cannot get it to work on local network connected via wifi or LAN. 

I am using this from the documentation
`python -m waifu2x.web --bind-addr 0.0.0.0 --port 8812`

And I go to my other computer and do http://10.0.0.6:8812/ and it cannot reach. I can however access Stable diffusion (using another app) with same ip just fine. I also made a firewall rule for incoming port of 8812 on the pc but nothing seems to work. 

I am also on windows.

I am using the [nunif-windows.zip](https://github.com/nagadomi/nunif/releases/download/0.0.0/nunif-windows.zip) from your release page.

**Comment by nagadomi** [comment]
I tried `python -m waifu2x.web --bind-addr 0.0.0.0` on Windows VM and it was successfully reached from the host OS.
When first ran, Windows Defender displayed a dialog box that asked to allow network connections, I had to click OK.

So I think that this problem is caused by your network environment at the moment.

1. Did you try using the same port as the Stable Diffusion? (--port 7860)
2. Did you successfully access `http://10.0.0.6:8812/`(not `http://127.0.0.1:8812/`) from local machine?
