### ISSUE TITLE
[unlimited:waifu2x] swin_unet models are very large and complex compared to cunet

### ISSUE THREAD

**Issue by LoganDark** [nagadomi/nunif#35]
I think there is something going on with the swin_unet models. They are much larger and slower than the cunet models.

<details><summary>Here is an image of the cunet scale2x model: tall netron graph</summary>

![image](https://user-images.githubusercontent.com/4723091/236655863-f8680350-cd14-410f-bd24-641846f56ddd.png)

</details>

not too bad right?

<details><summary>swin_unet scale2x: extremely tell netron graph</summary>

![image](https://user-images.githubusercontent.com/4723091/236655878-9ca04886-6aa5-4a45-ace7-57494f85d8a5.png)

</details>

***What*** is going on here. is this intended? I always used cunet for upscaling because I thought it was the more recent / higher quality version, but if swin_unet is supposed to be the better one, it shouldn't be so slow.

## Experiment

Firefox, SharedArrayBuffer enabled (12 threads). upscale 2x, denoise highest (3), TTA off, alpha off

Tile size 64, 280 tiles:
Cunet (tile_size = 84): 9376ms
Swin_unet (art_scan, tile_size = 64): 12355ms 

Tile size 256, 12 tiles:
Cunet (tile_size = 276): 5807ms
Swin_unet (art_scan, tile_size = 256): 16415ms

Tile size 400, 6 tiles:
Cunet (tile_size = 420): 6964ms
Swin_unet (art_scan, tile_size = 400): 21648ms

it looks like swin_unet gets exponentially expensive at high tile sizes, whereas cunet can benefit depending on how well the image pads.

This makes swin_unet look bad, but swin_unet is supposed to be the "next generation" model.

I am not sure if it is possible to do anything about this. There may be a good reason...

**Comment by nagadomi** [comment]
It is by design. waifu2x's model is getting slower with each update.
`upconv_7`(not included in unlimited:waifu2x) is more than twice as fast as cunet.
However, GPU processing speed improvements are even faster than that, so actual processing times have not changed much.
CPU processing speeds have not changed much in the past 10 years, so processing on CPU is getting slower and slower.

Basically that there is a tradeoff between complex/slower/more parameters and better upscaling results.
I posted scores at https://github.com/nagadomi/nunif/issues/6#issuecomment-1414582318

Also, in `swin_unet/photo` and `swin_unet/art_scan` models, 2x or 1x processing uses the 4x model internally, which is slower than `swin_unet/art`'s 1x or 2x.

**Comment by nagadomi** [comment]
waifu2x.udp.jp processes about 100,000 image requests per day.
It is over 1 FPS, so I think it is not too slow.
