### ISSUE TITLE
iw3 as a standalone exe

### ISSUE THREAD

**Issue by tufeixp** [nagadomi/nunif#70]
Why not build iw3 as a standalone exe!

**Comment by nagadomi** [comment]
I believe `iw3-gui.bat` in windows package is the same as a standalone exe. 
https://github.com/nagadomi/nunif/blob/master/windows_package/docs/README.md
It can be launched simply with double-click. 
And, it is better than exe because it is in text format. You can verify for yourself that it is not  a malware.

**Comment by tufeixp** [comment]
Well, I mean a packed exe which is ready for downloading and distribution, eg. on an USB disk.

**Comment by nagadomi** [comment]
You can simply zip/copy the entire folder after running install.bat. It is portable.
The reason it is an online installer is because the zip file is very large (2GB<). It exceeds the Github Release file size limit (2GB>).

The file size problem can be solved by using 7z at the present moment.
However, 7z is not bundled with Windows, so additional 7z installation is required.
It is also possible that the size of the PyTorch distribution will grow in the future, again exceeding the limit.
