### ISSUE TITLE
iw3 performance bottleneck

### ISSUE THREAD

**Issue by alanzchen** [nagadomi/nunif#77]
Hi @nagadomi,

Thank you for your fantastic work! Your tools have enabled me to revive some old memories in 3D on the Apple Vision Pro. 

I am currently running iw3 on an RTX 3090 and Ryzen 5 5600X. When converting a 1080p video with the settings I've used (see screenshot), I only get around 3 fps performance. You will notice that neither the CPU nor the GPU is consistently fully utilized. I have already set the batch sizes to their maximum values and the files are stored on a high-speed SSD.

Do you have any general performance tips for users? For instance, any advice related to setting batch sizes or other modifications would be greatly appreciated.

![CleanShot 2024-02-22 at 16 37 24@2x](https://github.com/nagadomi/nunif/assets/2144783/ec45e0aa-94bd-4fd7-82ff-fc2ef5c912a6)

**Comment by nagadomi** [comment]
On Windows there may be some performance issues.
I tried the same settings except Depth Batch Size(I used 16) with GTX 3070Ti on Linux and it was 6.5 FPS.

One thing I notice in the screenshot is that GPU Memory is shown as 48 GB.
Not familiar with Windows, but it may be a feature called Virtual VRAM on Windows and VRAM may be swapping.
Could you try `Depth Batch Size` set to 16 or 8?

---
GPU utilization
Windows TaskManager does not show GPU utilization with CUDA by default.
See https://michaelceber.medium.com/gpu-monitoring-on-windows-10-for-machine-learning-cuda-41088de86d65

---
I also realize the problem of FPS drops with high resolution input. I am currently trying to address that.

Also, 60FPS output will take two times longer to process than 30FPS.
This may be improved using frame interpolation of Depth, but it is still just an idea.

**Comment by alanzchen** [comment]
I will try depth batch size 16 for the next current conversion task to see if that helps.

Here is the `nvidia-smi` output. The usage statistics are pretty stable, so you could view it as a representative snapshot. 3090 has 24G VRAM, and I guess it should be correctly recognized by the system as "dedicated GPU memory". It's not fully used up either, I only hope Windows is not so dumb to use Virtual VRAM when there are still some VRAM available.

![CleanShot 2024-02-22 at 23 29 26@2x](https://github.com/nagadomi/nunif/assets/2144783/c5aec9da-db3b-48a4-a270-944b66a28b45)

**Comment by nagadomi** [comment]
GPU utilization was around 50%. I will check on this as well, as it is lower than I expected.
![nvidia-smi](https://github.com/nagadomi/nunif/assets/287255/b2692efd-3b8d-40c4-80b7-7d84e382adef)


Regarding CPU, at least one core is fully utilized.
That was 400% on 16 cores.

**Comment by nagadomi** [comment]
I have updated the code.
In my env (RTX 3070Ti Linux, Any_B), FPS has improved about 2x.
1920x1080 video: 6.5 FPS -> 13 FPS
720x720     video: 22 FPS -> 38 FPS

Also, `Stereo Batch Size` option is removed. It uses the same value as `Depth Batch Size`.

**Comment by nagadomi** [comment]
I have made minor additional improvements on Windows.
On Windows 2022 Server NVIDIA Tesla L4 env,
1920x1080 video: 2.7 FPS -> 5.3 FPS

Both the performance problem on Windows and the low GPU utilization problem seem to be caused by blocking device memory transfers (CPU <-> GPU).

**Comment by nagadomi** [comment]
I added `--max-workers` option (`Worker Threads` on GUI).
If this option is a non-zero value, inference is performed on the multi thread pool.

Typically, `Worker Threads = 2` is a good choice.
However, `Worker Thread = 8, Batch Size = 2` was the fastest for processing 1080p video on Windows.
My Windows test env does not have SSD, so I do not know if this is due to Windows OS or slow disk.

current result:
On Linux RTX 3070ti
1920x1080 video: 6.5 FPS -> 17 FPS
On Windows NVIDIA L4
1920x1080 video: 2.7 FPS -> 6.5 FPS


For now, there are no more improvements that can be made quickly and easily.

**Comment by gituser123456789000** [comment]
I know this is a month old and probably figured out by now, but my thought by looking at the settings is definitely Batch Size 64 is too high. I have a 4090 and the program crashed (error message popup and didn't run) when I did a test to find my ideal Depth Batch Size and Worker Threads.

Here are quotes of messages in a discord when I was doing testing for myself:

"I understand Depth Batch Size now that I tested with some video. Pay attention to the bottom left when you're processing a video.. it shows the frames like 324 / 88000.. Batch is just how many frames get processed before I suppose the temp file is updated.. so it's slowest at 1, because it processes a frame, then updates the file 325/88000.. processes a frame, then updates the file 326/88000... but setting a higher batch number, it will process that amount of frames before updating the file.. so 16 for example.. process 16 frames, update the file 340/88000.. process 16 frames, update the file 356/88000. I haven't checked hardware usage levels, but speed gains are there. For example this test, Batch of 1 I was getting 9.3FPS.. Batch 2 was around 9.6FPS.. Batch 4 about 10.2FPS... Batch 8, 16 about 10.3FPS... Batch 32 only got to nearly 10.0FPS.. Batch 64 didn't work, error message"

"Worker Threads 0 was 10.3FPS.... Worker Thread 2, 3, 4, 8 were all about 13.0FPS.... Worker Threads 16. started to dip at 12.7FPS.. 
So test your own hardware, just set up processing a video and watch the FPS on the bottom left. Start with Batch and Worker Threads at 0 0.. and change the values one at a time.. Start.. watch it for a little, like 20-30 seconds or however long, because it climbs a little over time.. Cancel. Wait for it to finish canceling.. change to the next value.. Start.. watch your FPS... Cancel."

So for my current hardware, I picked the middle of my best results for each of these values.. I use Depth Batch Size 8 and Worker Threads 4.

**Comment by nagadomi** [comment]
Now I fixed a major performance problem.

On Linux RTX 3070ti
1920x1080 video: 18 FPS -> 35 FPS
On Windows NVIDIA L4
1920x1080 video: 7 FPS -> 18 FPS

**Comment by gituser123456789000** [comment]
> Now I fixed a major performance problem.
> 
> On Linux RTX 3070ti 1920x1080 video: 18 FPS -> 35 FPS On Windows NVIDIA L4 1920x1080 video: 7 FPS -> 18 FPS

Very big performance upgrades confirmed (using 4090)
Pan's Labyrinth 1080 AnyLv2:
3.62FPS before > 4.43FPS after

Willy Wonka 1080p v2 Any L, then Any B, then Any S:
3.75 > 4.60 AnyLv2 before > after
6.65 > 10.37 AnyBv2 before > after
8.15 > 16.95 FPS AnySv2 before > after

exporting the same folder of depth maps:
4.06FPS before > 6.06FPS after
and verified the depth map quality.. yes, is the same

**Comment by nagadomi** [comment]
This is more of a problem fix than an improvement.
Previously, when transferring device memory between GPU<->CPU, the memory layout was not contiguous, resulting in unnecessary random accesses and that caused slowdowns. 
It is a change in only the internal memory layout, the program works exactly the same.
I thought iw3 was fast enough so I didn't notice that this big performance problem still existed.

There is still a performance gap between Linux and Windows, but that gap should narrow when pytorch 2.4.1 is released. In pytorch 2.4, AVX2/AVX512 is enabled in the Windows binary. However, 2.4.0 is currently unavailable due to a bug #189.
