### ISSUE TITLE
About model RowFlowV2

### ISSUE THREAD

**Issue by md5xwl** [nagadomi/nunif#99]
I try to play rgbd video on mobile device. 
The model file of RowFlowV2 is only 70kb, and I think it can be run on a mobile phone after quantization.
But, running on cpu 10900K with onnx fp16,  1x3x536x536  one frame need 50ms.
So I don't think the current model can run on a mobile phone fast.
I check the code,   RowFlowV2 use kernel_size=(1, 9), so It is must be 9?
Have you tried using kernel_size = 1x3 ？

**Comment by nagadomi** [comment]
In the previous version, large receptive field was required because the original resolution images were input into the model. I assumed 1920x1080 for the input size.
In the current version, the resolution input to the model is 392 (by default), so I think it is possible to reduce the kernel size or the number of layers.
However, the resolution can be increased by option, so there may be a problem if it is too small.
If you limit the depth resolution in your application then kernel_size=1x3 should be fine I think.
